### ISSUE TITLE
Reverse order of versions displayed

### ISSUE THREAD

**Issue by salim-b** [jmooring/hvm#12]
First, thank you very much for developing and releasing HVM as open source software! Neat little tool.

Now to my small feature request: I think it would make more sense to display the available Hugo versions in *reverse* order. Most of the time, users want to get the latest version (or a few releases behind that) when running `hvm use`. Currently, the latest version is also the last one displayed.

To be consistent, I'd recommend to also reverse the order of installed Hugo versions in `hvm status`.

**Comment by jmooring** [comment]
I'm glad you find it useful. 95% of my terminal activity is within VS code, where the terminal window is maybe 10 or 12 lines. I also set `numtagstodisplay` to a much higher number than the default value of 30.  Combining both factors, if they were sorted in descending order I would have to scroll up to the get to the latest release.

**Comment by salim-b** [comment]
Ok, that makes sense in this particular use case. In regular terminal usage with 80+ line width, I think the other way round would be more appropriate. This would be in line with how [`gh install`](https://github.com/redraw/gh-install) displays versions.

So, having a config option like `reverseVersionsInDisplay` (boolean) with your preferred setting as the default would be great!
