### ISSUE TITLE
Add command flag to `hvm install` that honors Hugo version in existing `.hvm` file

### ISSUE THREAD

**Issue by salim-b** [jmooring/hvm#21]
Add an additional command flag like `--use-existing`[^better] that lets hvm read an already existing `.hvm` file and install the recorded Hugo version if it is not already in the global cache (plus print a message that it succeeded in doing so). If no – or no valid – `.hvm` file exists, `hvm install --use-existing` should fail with an informative message. If a valid `.hvm` file exists and the recorded Hugo version is already in the cache, hvm should print a message that the requested Hugo version is already available and exit (with code `0`).

This requires https://github.com/jmooring/hvm/issues/19 to be implemented first. Then it would allow hvm to be used in any Hugo project repo to hardcode/synchronize the recommended/tested Hugo version.

[^better]: You will probably come up with a better name.

**Comment by jmooring** [comment]
@salim-b I would appreciate it if you could test the latest additions before I roll another release.

```
go install github.com/jmooring/hvm@HEAD
```

**Comment by salim-b** [comment]
Thanks @jmooring, the latest additions look great! See the additional issues I've opened for some small suggestions.

**Comment by jmooring** [comment]
@salim-b 

```text
hvm install --useVersionInDotFile
```
With a help description "Install the version specified in the .hvm file"
Thoughts?

**Comment by salim-b** [comment]
Do you plan on extending `hvm install` to other version tag sources? `--useVersionInDotFile` seems overly verbose since the only place where hvm stores version tags and reads them from is dot files... but I have a hard time coming up with something that doesn't include `dotFile`... 😅

Maybe just `--useDotFile` or **`--fromDotFile`**? The plus of the latter is that it doesn't evoke misleading associations with the `hvm use` command.

> With a help description "Install the version specified in the .hvm file"

I'd be a bit more verbose here and change this to `Install the version specified in the current directory's .hvm file`. The command descriptions of `hvm use` and `hvm disable` also mention "the current directory".

**Comment by salim-b** [comment]
Addendum: The `hvm install` command's description also needs to be changed. Currently it says:

> Install a default version to use when version management is disabled
 
Actually, a lot more intuitive would be to have
- a `hvm default` command to set the default Hugo version to use when no `.hvm` file exists in the current dir, and
- the `hvm install` command just do what `hvm install -useVersionInDotFile` is supposed to.

But you might disagree. 😄

**Comment by jmooring** [comment]
> Actually, a lot more intuitive would be to have

Not gonna do that for a bunch of reasons.

Also, I think the `hvm install --useVersionInDotFile` is a feature most users won't need, so I really don't care about the verbosity of the flag.

**Comment by salim-b** [comment]
Another suggestion: `hvm install` -> `hvm use --default`

That would also be more intuitive. An free up `hvm install`, obviously.

**Comment by jmooring** [comment]
Again, no. If people want to use this as a standalone installer, the most intuitive command is... install.

**Comment by salim-b** [comment]
But the tool's name is Hugo Version Manager, not Hugo Installer. 😶

**Comment by jmooring** [comment]
We're done with this one.
