### ISSUE TITLE
Let hvm generate the alias shell code via new `hvm gen alias` command

### ISSUE THREAD

**Issue by salim-b** [jmooring/hvm#22]
Currently, users have to consult the [README](https://github.com/jmooring/hvm#step-2---create-an-alias) to set up the required shell alias. The shell snippets for the different platforms could instead be generated by hvm (at build time, I guess) via a new command like `hvm alias`.

Motivations for this [include](https://github.com/jmooring/hvm/issues/19#issuecomment-1726197220):

> 1. Simplify this step of the installation.
> 2. Uncouple this step of the installation from the README.

**Comment by jmooring** [comment]
Depends on #20.
