### ISSUE TITLE
Remove the redundant global `--version` flag

### ISSUE THREAD

**Issue by salim-b** [jmooring/hvm#26]
Currently, hvm has a `hvm version` subcommand as well as global flag `--version`. I suggest to remove the latter because:

1. It's redundant and thus potentially confusing.
2. It doesn't work in subcommands, although it is displayed in the help of all of them.

**Comment by jmooring** [comment]
I will remove the -v/--version flag from the subcommands, but will keep it for the root command. Reasoning:
1. It is common in shell scripts to use `someapp -v` to verify that an app is installed
2. I dislike having to guess an app's help flag/command
3. Others apps do the same (e.g., Docker)
