### ISSUE TITLE
cmd/status: Differentiate between invalid and uninstalled versions 

### ISSUE THREAD

**Issue by salim-b** [jmooring/hvm#35]
Thanks again for all the recent changes/improvements around https://github.com/jmooring/hvm/issues/19!

I have another issue: If `hvm status` is run in a directory that contains an `.hvm` file with a version that is currently not available from the cache, the following message is displayed:

> Error: the .hvm file in the current directory contains an invalid version (vX.Y.Z): run `hvm use` to select a version, or `hvm disable` to remove the file

Users can find themselves in this state when
- using hvm to keep the Hugo version in sync in a version-controlled folder and having pulled an updated `.hvm` file that was modified on another machine.
- having run `hvm clean` in another directory. `hvm clean` deletes a possibly existing `.hvm` file, but only in the current directory[^deb].
- the user-cache directory where the hvm cache lives is purged for some reason (clean up tools etc.).
- migrating to another machine.

Would it be possible for hvm to display a modified error message if the `.hvm` file's content matches a Hugo version tag? I think it would suffice to simply check whether it matches the pseudo-regex pattern `^v(semantic_version)$` and do not actually check if the version tag corresponds to a real Hugo release. If no match is found, the current error message above should be displayed. Otherwise the following error:

> Error: the Hugo version registered in the `.hvm` file (vX.Y.Z) is currently not available in the cache: run `hvm use` to install this version to the cache, or `hvm disable` to remove the file

That would give a smoother UX, I think. 🙂

[^deb]: Personally, I'd prefer it if `hvm clean` would leave `.hvm` files untouched and leave that clean up task solely to `hvm disable`.

**Comment by jmooring** [comment]
> I'd prefer it if hvm clean would leave .hvm files untouched 

Yeah, I waffled on this one a bit, not wanting to leave a user in half-way state. But they're still in a half-way state for other version managed directories, so consistency is probably better. I'll pull this into a separate issue.

And FYI, while you're testing, you can use the hidden `hvm reset` command. See `hvm reset --help`.

**Comment by jmooring** [comment]
Instead of throwing this error...

> Error: the .hvm file in the current directory refers to a version (v0.111.0) that does not exist in the cache: run "hvm install --useVersionInDotFile" to install, or "hvm disable" to remove the file

Let's print to stdout...

> The .hvm file in the current directory refers to a version (v0.111.0) that does not exist in the cache. Would you like to install it?

Then install.

**Comment by salim-b** [comment]
That'd be great! I didn't dare to ask... 😅

**Comment by jmooring** [comment]
> for now do nothing, we can revisit as needed

If they say no, we need to remove the .hvm file (disable version management in the current directory).

@salim-b 

Can you build and test from a PR?

**Comment by salim-b** [comment]
> Can you build and test from a PR?

I guess so :)

**Comment by jmooring** [comment]
@salim-b Hold off.

**Comment by jmooring** [comment]
@salim-b When you have a moment, please pull changes and build from source, then generate a new alias script.

There's a breaking change...

The `hvm install --useVersionInDotFile` was not the right approach; it caused the default installation to be overwritten.

Use `hvm use --useVersionInDotFile` instead. The new alias script takes care of this for you. If you have a dot file with a version that is not cached, it will automatically download it when you run `hugo anything`.

I'm pretty happy with the way it's working now, but let me know if you find anything.

**Comment by salim-b** [comment]
Impressively convenient! ☺️

What I noticed:

- hvm doesn't ask whether to install a Hugo version that is not in the cache. It just does it. I like that!

- If a Hugo version is registered in the `.hvm` file which is not (yet) released (or outright invalid), hvm prints the following message:

  > Error: GET https://api.github.com/repos/gohugoio/hugo/releases/tags/v0.119.0: 404 Not Found []
  > bash: /home/salim/.cache/hvm/v0.119.0/hugo: No such file or directory

  This is actually an hvm-internal error which doesn't address the user. But I guess this falls into the "luxury problem" category.

**Comment by jmooring** [comment]
Thanks for testing.

When running the alias function:

1. If the dot file content is a valid semver, but not available in the repo, we will exit gracefully. See #40.
2. If the dot file is empty or the content is not a valid semver, the exit isn't great, but (a) this scenario is even less likely, and (b) I really don't want to make alias script any more complex than it already is. I'll think about it...
